export const data = [
  {
    name: "Fiitjee PCM modules (30+ modules)",
    price: "600.00",
    mrp: "6000.00",
    status: "Available",
    tags: ["JEE"],
  },
  {
    name: "Fiitjee PCM Grand Master Package",
    price: "900.00",
    mrp: "6000.00",
    status: "Available",
    tags: ["JEE"],
  },
  {
    name: "Fiitjee PCM Archive",
    price: "600.00",
    mrp: "2000.00",
    status: "Available",
    tags: ["JEE"],
  },
  {
    name: "Matrix PCM Question Bank",
    price: "150.00",
    mrp: "2000.00",
    status: "Available",
    tags: ["JEE"],
  },
  {
    name: "HC Verma Concepts of Physics Part 1",
    price: "100.00",
    mrp: "500.00",
    status: "Sold",
    tags: ["JEE", "physics"],
  },
  {
    name: "HC Verma Concepts of Physics Part 2",
    price: "100.00",
    mrp: "500.00",
    status: "Sold",
    tags: ["JEE", "physics"],
  },
  {
    name: "Modern approach to chemical calculations R.C. Mukerjee",
    price: "100.00",
    mrp: "205.00",
    status: "Booked",
    tags: ["JEE"],
  },
  {
    name: "Arihant play with graphs",
    price: "100.00",
    mrp: "200.00",
    status: "Sold",
    tags: ["JEE"],
  },
  {
    name: "Arihant handbook of chemistry",
    price: "100.00",
    mrp: "250.00",
    status: "Sold",
    tags: ["JEE"],
  },
  {
    name: "SL Arora Physics XI",
    price: "500.00",
    mrp: "1300.00",
    status: "Available",
    tags: ["science", "physics"],
  },
  {
    name: "SL Arora Physics XII",
    price: "500.00",
    mrp: "1500.00",
    status: "Available",
    tags: ["science", "physics"],
  },
  {
    name: "Pradeeps Chemistry XII",
    price: "200.00",
    mrp: "1000.00",
    status: "Available",
    tags: ["science", "chemistry"],
  },
  {
    name: "IP University BTech Entrance Exam",
    price: "100.00",
    mrp: "500.00",
    status: "Available",
    tags: ["engineering"],
  },
  {
    name: "BArch Entrance Exam",
    price: "100.00",
    mrp: "300.00",
    status: "Available",
    tags: ["barch"],
  },
  {
    name: "DC Pandey Physics for JEE",
    price: "100.00",
    mrp: "400.00",
    status: "Sold",
    tags: ["JEE", "physics"],
  },
  {
    name: "Rakesh Yadav SSC Maths",
    price: "100.00",
    mrp: "450.00",
    status: "Sold",
    tags: ["SSC", "maths"],
  },
  {
    name: "Let us C by Yashwant Kanetkar",
    price: "100.00",
    mrp: "250.00",
    status: "Sold",
    tags: ["coding"],
  },
  {
    name: "GATE Electrical Engineering",
    price: "100.00",
    mrp: "900.00",
    status: "Available",
    tags: ["engineering", "electrical"],
  },
  {
    name: "Modern digital electronics by RP Jain",
    price: "250.00",
    mrp: "700.00",
    status: "Available",
    tags: ["engineering", "electronics"],
  },
  {
    name: "Operating Systems by Galvin",
    price: "150.00",
    mrp: "800.00",
    status: "Available",
    tags: ["coding", "os"],
  },
  {
    name: "Automatic Control Systems by Hassan Saeed",
    price: "150.00",
    mrp: "500.00",
    status: "Available",
    tags: ["engineering"],
  },
  {
    name: "MadeEasy GATE 2013 Engineering Mathematics",
    price: "100.00",
    mrp: "500.00",
    status: "Available",
    tags: ["engineering", "maths"],
  },
  {
    name: "Electronics Principles Malvino Bates",
    price: "100.00",
    mrp: "400.00",
    status: "Sold",
    tags: ["engineering", "electronics"],
  },
  {
    name: "Electronic devices and circuits GATE Notes",
    price: "100.00",
    mrp: "200.00",
    status: "Available",
    tags: ["engineering", "electronics"],
  },
  {
    name: "Analog Electronics GATE Notes",
    price: "100.00",
    mrp: "200.00",
    status: "Available",
    tags: ["engineering", "electronics"],
  },
  {
    name: "8051 Microcontroller Architecture Programming and Interfacing",
    price: "100.00",
    mrp: "500.00",
    status: "Sold",
    tags: ["engineering", "electronics"],
  },
  {
    name: "Micro Electronics Sedra Smith",
    price: "300.00",
    mrp: "1000.00",
    status: "Sold",
    tags: ["engineering", "electronics"],
  },
  {
    name: "Maths BTech First year",
    price: "50.00",
    mrp: "500.00",
    status: "Available",
    tags: ["engineering", "maths"],
  },
  {
    name: "12th physics ULike sample paper",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "physics"],
  },
  {
    name: "12th maths ULike sample paper",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "maths"],
  },
  {
    name: "12th maths togetherwith",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "maths"],
  },
  {
    name: "12th Python togetherwith",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["coding", "python"],
  },
  {
    name: "APC Physics Lab Manual XII",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "physics"],
  },
  {
    name: "Comprehensive chemistry Lab Manual XII",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "chemistry"],
  },
  {
    name: "APC chemistry Lab Manual XI",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "chemistry"],
  },
  {
    name: "Samar chemistry Lab Manual XI",
    price: "100.00",
    mrp: "400.00",
    status: "Available",
    tags: ["science", "chemistry"],
  },
  {
    name: "KV Support Material physics XII",
    price: "Free",
    mrp: "",
    status: "Sold",
    tags: ["science", "physics"],
  },
  {
    name: "Support Material physics XI XII",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["science", "physics"],
  },
  {
    name: "Support Material maths XI XII",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["science", "maths"],
  },
  {
    name: "Support Material maths X XI XII",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["science", "maths"],
  },
  {
    name: "Support Material science X",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["science"],
  },
  {
    name: "Support Material biology XI",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["science", "biology"],
  },
  {
    name: "Support Material english XI",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["english"],
  },
  {
    name: "Support Material Economics XI XII",
    price: "Free",
    mrp: "",
    status: "Available",
    tags: ["commerce", "economics"],
  },
  {
    name: "JPH Science guide IX",
    price: "100",
    mrp: "400",
    status: "Available",
    tags: ["science"],
  },
  {
    name: "RD Sharma IX",
    price: "150.00",
    mrp: "500.00",
    status: "Available",
    tags: ["9th", "maths"],
  },
  {
    name: "RD Sharma X",
    price: "150.00",
    mrp: "500.00",
    status: "Available",
    tags: ["10th", "maths"],
  },
  {
    name: "SChand Physics IX",
    price: "200.00",
    mrp: "500.00",
    status: "Sold",
    tags: ["9th", "physics"],
  },
  {
    name: "SChand Chemistry IX",
    price: "200.00",
    mrp: "500.00",
    status: "Sold",
    tags: ["9th", "chemistry"],
  },
  {
    name: "SChand Biology IX",
    price: "200.00",
    mrp: "500.00",
    status: "Available",
    tags: ["9th", "biology"],
  },
  {
    name: "SChand Physics X",
    price: "200.00",
    mrp: "500.00",
    status: "Sold",
    tags: ["10th", "physics"],
  },
  {
    name: "SChand Chemistry X",
    price: "200.00",
    mrp: "500.00",
    status: "Available",
    tags: ["10th", "chemistry"],
  },
  {
    name: "SChand Biology X",
    price: "200.00",
    mrp: "500.00",
    status: "Available",
    tags: ["10th", "biology"],
  },
  {
    name: "Pictionary board game",
    price: "200.00",
    mrp: "1000.00",
    status: "Available",
    tags: ["games"],
  },
  {
    name: "Microeconomics sandeep garg XII",
    price: "100.00",
    mrp: "300.00",
    status: "Sold",
    tags: ["commerce", "economics"],
  },
  {
    name: "Macroeconomics sandeep garg XII",
    price: "200.00",
    mrp: "300.00",
    status: "Sold",
    tags: ["commerce", "economics"],
  },
  {
    name: "corporate laws reena/sumant chaddha",
    price: "200.00",
    mrp: "355.00",
    status: "Sold",
    tags: ["commerce", "law"],
  },
  {
    name: "Analysis of financial statements TS Grewal XII (2015 ED.)",
    price: "100.00",
    mrp: "298.00",
    status: "Sold",
    tags: ["commerce", "finance"],
  },
  {
    name: "Analysis of financial statements TS Grewal XII (2018 ED.)",
    price: "200.00",
    mrp: "405.00",
    status: "Sold",
    tags: ["commerce", "finance"],
  },
  {
    name: "Double Entry TS Grewal XII (2018 ED.)",
    price: "200.00",
    mrp: "425.00",
    status: "Sold",
    tags: ["commerce", "accounting"],
  },
  {
    name: "Introductory Microeconomics TR Jain XII",
    price: "150.00",
    mrp: "245.00",
    status: "Sold",
    tags: ["commerce", "economics"],
  },
  {
    name: "APC Economics Sample Papers XII",
    price: "150.00",
    mrp: "250.00",
    status: "Sold",
    tags: ["commerce", "economics"],
  },
  {
    name: "BCom(H) Sem 1 Business laws Rajni Jagota",
    price: "200.00",
    mrp: "360.00",
    status: "Sold",
    tags: ["commerce", "bcom"],
  },
  {
    name: "BCom(H) Shivdas Semester 1 (Financial Accounting, Introduction to Microeconomics)",
    price: "100.00",
    mrp: "200.00",
    status: "Available",
    tags: ["commerce", "bcom"],
  },
  {
    name: "BCom(H) Shivdas Semester 6 (GST, Fundamentals of Investment, International Business, Auditing and coporate governance)",
    price: "200.00",
    mrp: "400.00",
    status: "Available",
    tags: ["commerce", "bcom"],
  },
  {
    name: "JPH English Grammar",
    price: "200.00",
    mrp: "500.00",
    status: "Available",
    tags: ["english", "grammar"],
  },
  {
    name: "Hindi Grammar",
    price: "50.00",
    mrp: "300.00",
    status: "Available",
    tags: ["hindi", "grammar"],
  },
  {
    name: "Her last wish",
    price: "100.00",
    mrp: "200.00",
    status: "Available",
    tags: ["novels"],
  },
  {
    name: "You can win by Shiv Khera",
    price: "150.00",
    mrp: "400.00",
    status: "Available",
    tags: ["novels", "self-help"],
  },
  {
    name: "Your name",
    price: "150.00",
    mrp: "1000.00",
    status: "Available",
    tags: ["novels"],
  },
  {
    name: "Gaban premchand",
    price: "100.00",
    mrp: "200.00",
    status: "Available",
    tags: ["novels", "literature"],
  },
]