on:
  workflow_dispatch: # To trigger workflow manually
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Profile Readme Stats Mod
      uses: tarunesh1234/profile-readme-stats-mod@v1.2.0
      with:
        token: ${{ secrets.USER_TOKEN }}
        includeForks: true
        includeOrgRepos: true
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
